AI_Decryption/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("index.urls")),
]

index/urls.py
from django.urls import path
from . import views

app_name = "index"
urlpatterns = [
    path("", views.blank, name="blank"),
    path("index", views.index, name="index"),
    path("decrypt", views.decrypt, name="decrypt"),
]

index/models.py
from django.db import models

# Create your models here.

index/views.py
from django.shortcuts import render, redirect
from django.urls.base import reverse_lazy
from ciphey import eval_encryption

# Create views here.
def blank(request):
    url = reverse_lazy("index:index")
    return redirect(url)

def index(request):
    return render(request, "index/index.html")

def decrypt(request):
    if request.method == "POST":
        encrypted_text = str(request.POST["encrypted_text"])

        if encrypted_text == "":
            return render(request, "index/decrypt.html", 
            {"result": "*Empty string is not allowed*", "error": 1})
        
        result, error = eval_encryption(encrypted_text)
        
        if error == 0:
            return render(request, "index/decrypt.html", {"result": result})
        else:
            return render(request, "index/decrypt.html", {"result": result, "error": error})
    else:
        return render(request, "index/decrypt.html")

index/templates/index/decrypt.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <link href="{% static 'index/decrypt.css' %}" rel="stylesheet">
        <script src="{% static 'index/decrypt.js' %}"></script>
        <title>AI Decrypt- Main</title>
    </head>

    <body>
        <div class="greet-container">
            <div class="greet-content">
                <p class="greet-content-font">
                    Please enter your encrypted text here
                </p>

                <div style="height: 15px;"></div>

                <form method="post" class="form-container cell" id="form-container">
                    {% csrf_token %}
                    <div class="cell">
                        <input type="text" name="encrypted_text" 
                        placeholder=" sample text" class="input-1">
                    </div>

                    {% if result %}
                    <div class="cell">
                        <button type="submit" class="btn-3" disabled>
                            
                        </button>
                    </div>
                    {% else %}
                    <div class="cell">
                        <button type="submit" class="btn-1" id="btn-1"
                        onclick="showWheel(); disableButton()">
                            Decrypt
                        </button>
                    </div>
                    {% endif %}
                </form>
                
                <div style="height: 20px;"></div>

                <a class="btn-2" href="{% url 'index:index' %}">To Home</a>
                <a class="btn-2" href="{% url 'index:decrypt' %}">Restart/Kill</a>

                <div style="height: 60px;"></div>
            </div>
        </div>
        
        {% if result %}
        <!-- Do nothing -->
        {% else %}
        <div class="load-text-container">
            <div class="dual-ring-container">
                <div class="dual-ring"></div>
            </div>
            <div class="load-text"></div>
        </div>
        {% endif %}

        {% if result %}
        <div class="result-container">
            <a class="result-content">
                <p class="result-title">The Answer: </p>
                {{ result }}
            </a>
        </div>
        {% else %}
        <div class="result-container">
            <div class="result-content" 
            style="font-weight:normal;text-align:center;min-height:40px;">
                Over 250 characters may cause error
            </div>
        </div>
        {% endif %}

        {% if error %}
        <body onload="error()"></body>
        {% else %}
        <!-- Do nothing -->
        {% endif %}
    </body>
</html>

index/templates/index/index.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <link href="{% static 'index/index.css' %}" rel="stylesheet">
        <title>AI Decrypt- Home</title>
    </head>

    <body>
        <div class="greet-container">
            <div class="greet-content">
                <p class="greet-content-font">
                    Hello, this is a tool that helps you to decrypt encoded text using<br>
                    AI engines that can recognize many common algorithms.
                </p>

                <div style="height: 30px;"></div>

                <a class="btn-1" href="{% url 'index:decrypt' %}">Get started &#8594;</a>
            </div>
        </div>
    </body>
</html>